### PR TITLE
AND_1.0.3: send REFUSED only when the token already exists.

### PR DESCRIPTION
**Pull request by p1gp1g**

### CODE REVIEW

**Comment by p1gp1g** [comment]
Is that ok for you ? Should we do the same for dbus ?

**Comment by sparchatus** [comment]
I would suggest to also allow sending REFUSED when the distributor for whatever reason (i.e. user blocked the app) does not want to provide UP functionality to some application.

**Comment by p1gp1g** [comment]
Maybe the best is simply to remove REFUSED and always use FAILED (for dbus and android). "Refused" and/or the reason why can be sent has its extra

**Review by karmanyaahm — APPROVED** [review]
~~Based on https://github.com/UnifiedPush/specifications/pull/17#issuecomment-1004010232 this makes sense~~

Actually, no #18 is probably better since that simplifies things. I'll comment further on there

**Review by sparchatus — APPROVED** [review]

**Pull request closed without merging**
